const config = {
    LOTTERY_GAME_CONTRACT_ADDRESS: process.env.LOTTERY_GAME_ADDRESS,
    LOTTERY_GAME_NFT_CARD_CONTRACT_ADDRESS: process.env.LOTTERY_GAME_NFT_CARD_ADDRESS,
    LOTTERY_GAME_SETTING_CONTRACT_ADDRESS: process.env.LOTTERY_GAME_SETTING_ADDRESS,
  }
  
  export default config;